"""
GVHMR Maya Importer

Load a GVHMR bundle generated by ComfyUI-MotionCapture and build a Maya scene:
- import an FBX or Alembic body if present
- create/keyframe the GVHMR camera from camera_maya.json

Run in Maya's Script Editor:

    import gvhmr_maya_importer
    gvhmr_maya_importer.show()
"""

import json
import os
import struct
from array import array

import maya.cmds as cmds
import maya.api.OpenMaya as om


WINDOW_NAME = "gvhmrMayaImporterWindow"
SMPLX_JOINT_RADIUS = 0.05


CAMERA_X_FLIP_MATRIX = [
    1.0, 0.0, 0.0, 0.0,
    0.0, -1.0, 0.0, 0.0,
    0.0, 0.0, -1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
]


def _manifest_path(bundle_dir):
    return os.path.join(bundle_dir, "manifest.json")


def _resolve_bundle_file(bundle_dir, value):
    if not value:
        return ""
    if os.path.isabs(value):
        return value
    return os.path.abspath(os.path.join(bundle_dir, value))


def _load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _matmul4(a, b):
    out = [0.0] * 16
    for row in range(4):
        for col in range(4):
            out[row * 4 + col] = sum(a[row * 4 + k] * b[k * 4 + col] for k in range(4))
    return out


def _read_array(file_obj, typecode, count):
    data = array(typecode)
    data.frombytes(file_obj.read(count * data.itemsize))
    return data


def _try_load_plugin(name):
    try:
        if not cmds.pluginInfo(name, query=True, loaded=True):
            cmds.loadPlugin(name)
        return True
    except Exception:
        return False


def _safe_set_attr(attr, value):
    try:
        if cmds.objExists(attr):
            cmds.setAttr(attr, value)
    except Exception:
        pass


def _set_time_unit(fps):
    fps_int = int(round(float(fps)))
    time_units = {
        15: "game",
        24: "film",
        25: "pal",
        30: "ntsc",
        48: "show",
        50: "palf",
        60: "ntscf",
    }
    unit = time_units.get(fps_int, f"{fps_int}fps")
    try:
        cmds.currentUnit(time=unit)
    except Exception:
        cmds.warning(f"Could not set Maya time unit to {unit}")


def _import_body(bundle_dir, files):
    fbx_path = _resolve_bundle_file(bundle_dir, files.get("fbx", ""))
    abc_path = _resolve_bundle_file(bundle_dir, files.get("alembic", "") or files.get("abc", ""))
    glb_path = _resolve_bundle_file(bundle_dir, files.get("glb", ""))

    if fbx_path and os.path.isfile(fbx_path):
        _try_load_plugin("fbxmaya")
        cmds.file(
            fbx_path,
            i=True,
            type="FBX",
            ignoreVersion=True,
            mergeNamespacesOnClash=False,
            namespace="gvhmr",
            options="fbx",
            preserveReferences=True,
        )
        return fbx_path

    if abc_path and os.path.isfile(abc_path):
        _try_load_plugin("AbcImport")
        cmds.AbcImport(abc_path, mode="import")
        return abc_path

    if glb_path and os.path.isfile(glb_path):
        cmds.warning("Bundle contains GLB, but Maya does not import GLB by default. Provide an FBX or Alembic for direct Maya import.")
    else:
        cmds.warning("No FBX or Alembic body found in bundle.")

    return ""


def _convert_smpc_point(x, y, z):
    # SMPC vertices are in GVHMR/SMPL Y-up world space. Maya is also Y-up.
    return om.MPoint(float(x), float(y), float(z))


def _create_mesh_from_frame(mesh_name, vertices, faces, frame_index, num_verts, num_faces):
    if cmds.objExists(mesh_name):
        cmds.delete(mesh_name)

    offset = frame_index * num_verts * 3
    points = [
        _convert_smpc_point(vertices[offset + i * 3], vertices[offset + i * 3 + 1], vertices[offset + i * 3 + 2])
        for i in range(num_verts)
    ]
    face_counts = [3] * num_faces
    face_connects = [int(v) for v in faces]

    transform_name = cmds.createNode("transform", name=mesh_name)
    selection = om.MSelectionList()
    selection.add(transform_name)
    transform_obj = selection.getDependNode(0)

    mesh_fn = om.MFnMesh()
    mesh_obj = mesh_fn.create(points, face_counts, face_connects, parent=transform_obj)
    dag = om.MFnDagNode(mesh_obj)
    shape_path = dag.fullPathName()
    shape_name = f"{mesh_name}Shape"
    try:
        cmds.rename(shape_path, shape_name)
    except Exception:
        pass
    children = cmds.listRelatives(transform_name, shapes=True, fullPath=False) or []
    for child in children:
        if child.startswith("polySurface"):
            try:
                cmds.rename(child, shape_name)
            except Exception:
                pass
    return transform_name


def _create_mesh_from_positions(mesh_name, positions, faces):
    if cmds.objExists(mesh_name):
        cmds.delete(mesh_name)

    points = [_convert_smpc_point(point[0], point[1], point[2]) for point in positions]
    face_counts = [3] * len(faces)
    face_connects = [int(v) for face in faces for v in face]

    transform_name = cmds.createNode("transform", name=mesh_name)
    selection = om.MSelectionList()
    selection.add(transform_name)
    transform_obj = selection.getDependNode(0)

    mesh_fn = om.MFnMesh()
    mesh_obj = mesh_fn.create(points, face_counts, face_connects, parent=transform_obj)
    dag = om.MFnDagNode(mesh_obj)
    shape_path = dag.fullPathName()
    try:
        cmds.rename(shape_path, f"{mesh_name}Shape")
    except Exception:
        pass
    return transform_name


def _delete_existing_smplx_rig():
    for name in ("GVHMR_SMPLX", "GVHMR_SMPLX_Mesh", "GVHMR_SMPLX_Skeleton"):
        if cmds.objExists(name):
            try:
                cmds.delete(name)
            except Exception:
                pass


def _import_smplx_rig(bundle_dir, files, replace_existing=True):
    rig_path = _resolve_bundle_file(bundle_dir, files.get("maya_smplx_rig_json", ""))
    if not rig_path or not os.path.isfile(rig_path):
        cmds.warning("No Maya SMPLX skeletal rig payload found in bundle.")
        return ""

    data = _load_json(rig_path)
    joint_names = data["joint_names"]
    joint_parents = [int(value) for value in data["joint_parents"]]
    joint_positions = data["joint_positions"]
    mesh_positions = data["mesh_positions"]
    faces = data["faces"]
    skin_indices = data["skin_indices"]
    skin_weights = data["skin_weights"]
    animation = data.get("animation", {})
    root_translations = animation.get("root_translations", [])
    joint_eulers = animation.get("joint_eulers_xyz_deg", [])
    fps = float(data.get("fps", 24))

    if replace_existing:
        _delete_existing_smplx_rig()

    group = cmds.group(empty=True, name="GVHMR_SMPLX")
    skeleton_group = cmds.group(empty=True, name="GVHMR_SMPLX_Skeleton", parent=group)

    joints = []
    for name in joint_names:
        joint = cmds.createNode("joint", name=f"GVHMR_{name}_JNT")
        cmds.setAttr(f"{joint}.rotateOrder", 0)
        cmds.setAttr(f"{joint}.radius", SMPLX_JOINT_RADIUS)
        joints.append(joint)

    for index, joint in enumerate(joints):
        parent_index = joint_parents[index]
        if parent_index >= 0:
            cmds.parent(joint, joints[parent_index])
            offset = [
                float(joint_positions[index][axis]) - float(joint_positions[parent_index][axis])
                for axis in range(3)
            ]
        else:
            cmds.parent(joint, skeleton_group)
            offset = [float(value) for value in joint_positions[index]]

        cmds.setAttr(f"{joint}.translate", offset[0], offset[1], offset[2], type="double3")
        cmds.setAttr(f"{joint}.rotate", 0.0, 0.0, 0.0, type="double3")
        cmds.setAttr(f"{joint}.jointOrient", 0.0, 0.0, 0.0, type="double3")

    mesh = _create_mesh_from_positions("GVHMR_SMPLX_Mesh", mesh_positions, faces)
    cmds.parent(mesh, group)

    skin_cluster = cmds.skinCluster(
        joints,
        mesh,
        toSelectedBones=True,
        bindMethod=0,
        skinMethod=0,
        normalizeWeights=1,
        maximumInfluences=4,
        name="GVHMR_SMPLX_SkinCluster",
    )[0]

    for vertex_index, (indices, weights) in enumerate(zip(skin_indices, skin_weights)):
        transform_values = []
        for joint_index, weight in zip(indices, weights):
            weight = float(weight)
            if weight > 1e-6:
                transform_values.append((joints[int(joint_index)], weight))
        if transform_values:
            cmds.skinPercent(
                skin_cluster,
                f"{mesh}.vtx[{vertex_index}]",
                transformValue=transform_values,
                normalize=True,
            )

    _set_time_unit(fps)
    frame_count = min(len(root_translations), len(joint_eulers))
    if frame_count:
        cmds.playbackOptions(min=1, max=frame_count)

    for frame_index in range(frame_count):
        frame = frame_index + 1
        cmds.currentTime(frame, edit=True)
        root_translation = root_translations[frame_index]
        cmds.setAttr(
            f"{joints[0]}.translate",
            float(root_translation[0]),
            float(root_translation[1]),
            float(root_translation[2]),
            type="double3",
        )
        cmds.setKeyframe(joints[0], attribute=["translate"], time=frame)

        for joint_index, joint in enumerate(joints):
            rx, ry, rz = joint_eulers[frame_index][joint_index]
            cmds.setAttr(f"{joint}.rotate", float(rx), float(ry), float(rz), type="double3")
            cmds.setKeyframe(joint, attribute=["rotate"], time=frame)

    if frame_count:
        cmds.currentTime(1, edit=True)

    cmds.select(group, replace=True)
    return group


def _load_smpc_mesh_data(path):
    with open(path, "rb") as f:
        magic = f.read(4)
        if magic != b"SMPC":
            raise RuntimeError(f"Not an SMPC file: {path}")

        num_frames = struct.unpack("<I", f.read(4))[0]
        num_verts = struct.unpack("<I", f.read(4))[0]
        num_faces = struct.unpack("<I", f.read(4))[0]
        fps = struct.unpack("<f", f.read(4))[0]
        f.read(64)
        has_camera = struct.unpack("<I", f.read(4))[0]
        img_w = struct.unpack("<I", f.read(4))[0]
        img_h = struct.unpack("<I", f.read(4))[0]
        vertices = _read_array(f, "f", num_frames * num_verts * 3)
        faces = _read_array(f, "I", num_faces * 3)

    return {
        "num_frames": num_frames,
        "num_verts": num_verts,
        "num_faces": num_faces,
        "fps": fps,
        "has_camera": has_camera,
        "img_width": img_w,
        "img_height": img_h,
        "vertices": vertices,
        "faces": faces,
    }


def _import_smpc_mesh(bundle_dir, files, replace_existing=True, max_frames=240):
    smpc_path = _resolve_bundle_file(bundle_dir, files.get("smpc_bin", ""))
    if not smpc_path or not os.path.isfile(smpc_path):
        cmds.warning("No SMPC mesh cache found in bundle.")
        return ""

    data = _load_smpc_mesh_data(smpc_path)
    num_frames = int(data["num_frames"])
    num_verts = int(data["num_verts"])
    num_faces = int(data["num_faces"])

    if num_frames > max_frames:
        raise RuntimeError(
            f"SMPC mesh cache has {num_frames} frames. "
            f"This diagnostic importer is capped at {max_frames} frames."
        )

    mesh_name = "GVHMR_SMPL_Mesh"
    target_group = "GVHMR_SMPL_Targets"
    if replace_existing:
        for name in (mesh_name, target_group):
            if cmds.objExists(name):
                cmds.delete(name)

    base_mesh = _create_mesh_from_frame(mesh_name, data["vertices"], data["faces"], 0, num_verts, num_faces)
    targets = []
    if not cmds.objExists(target_group):
        target_group = cmds.group(empty=True, name=target_group)

    for frame_index in range(num_frames):
        target_name = f"GVHMR_SMPL_Frame_{frame_index + 1:04d}"
        target = _create_mesh_from_frame(target_name, data["vertices"], data["faces"], frame_index, num_verts, num_faces)
        cmds.parent(target, target_group)
        targets.append(target)

    blendshape = cmds.blendShape(*(targets + [base_mesh]), name="GVHMR_SMPL_BlendShape")[0]
    cmds.setAttr(f"{target_group}.visibility", 0)

    _set_time_unit(data["fps"] or 24)
    cmds.playbackOptions(min=1, max=num_frames)

    for idx in range(num_frames):
        attr = f"{blendshape}.w[{idx}]"
        frame = idx + 1
        for key_frame, value in ((max(1, frame - 1), 0.0), (frame, 1.0), (min(num_frames, frame + 1), 0.0)):
            cmds.setAttr(attr, value)
            cmds.setKeyframe(attr, time=key_frame)

    cmds.currentTime(1, edit=True)
    cmds.select(base_mesh, replace=True)
    return base_mesh


def _delete_existing_camera(camera_name):
    if cmds.objExists(camera_name):
        try:
            cmds.delete(camera_name)
        except Exception:
            pass


def _reference_media_path(bundle_dir, files):
    value = files.get("reference_video", "") or files.get("reference_image", "")
    if value:
        path = _resolve_bundle_file(bundle_dir, value)
        if os.path.isfile(path):
            return path

    smpc_path = _resolve_bundle_file(bundle_dir, files.get("smpc_bin", ""))
    if smpc_path:
        base, _ = os.path.splitext(smpc_path)
        for ext in (".mp4", ".mov", ".png", ".jpg", ".jpeg"):
            candidate = f"{base}_ref{ext}"
            if os.path.isfile(candidate):
                return candidate
    return ""


def _create_camera_reference_plane(camera_transform, camera_shape, media_path):
    if not media_path:
        return ""

    try:
        result = cmds.imagePlane(camera=camera_transform, fileName=media_path)
    except Exception as exc:
        cmds.warning(f"Could not create camera image plane from {media_path}: {exc}")
        return ""

    plane_shape = ""
    if isinstance(result, (list, tuple)) and result:
        plane_shape = result[-1]
    elif isinstance(result, str):
        plane_shape = result

    _safe_set_attr(f"{camera_shape}.displayResolution", 1)
    _safe_set_attr(f"{camera_shape}.displayFilmGate", 1)
    _safe_set_attr(f"{camera_shape}.displayGateMask", 1)
    _safe_set_attr(f"{camera_shape}.displayGateMaskOpacity", 0.5)
    _safe_set_attr(f"{camera_shape}.overscan", 1.0)

    if plane_shape:
        _safe_set_attr(f"{plane_shape}.displayMode", 3)
        _safe_set_attr(f"{plane_shape}.alphaGain", 0.7)

    return plane_shape


def _create_camera(camera_data, replace_existing=True, flip_x=True, reference_media_path=""):
    camera_name = camera_data.get("camera_name", "GVHMR_Camera")
    if replace_existing:
        _delete_existing_camera(camera_name)

    transform, shape = cmds.camera(name=camera_name)
    if transform != camera_name:
        transform = cmds.rename(transform, camera_name)
        shapes = cmds.listRelatives(transform, shapes=True, fullPath=False) or []
        shape = shapes[0] if shapes else shape

    img_w = int(camera_data.get("img_width", 1920))
    img_h = int(camera_data.get("img_height", 1080))
    fps = float(camera_data.get("fps", 24))
    sensor_width_mm = float(camera_data.get("sensor_width_mm", 36.0))
    frames = camera_data.get("frames", [])

    _set_time_unit(fps)
    if frames:
        cmds.playbackOptions(min=frames[0]["frame"], max=frames[-1]["frame"])

    cmds.setAttr("defaultResolution.width", img_w)
    cmds.setAttr("defaultResolution.height", img_h)
    cmds.setAttr(f"{shape}.horizontalFilmAperture", sensor_width_mm / 25.4)
    cmds.setAttr(f"{shape}.verticalFilmAperture", (sensor_width_mm * img_h / img_w) / 25.4)
    cmds.setAttr(f"{shape}.filmFit", 1)  # horizontal
    cmds.setAttr(f"{shape}.lensSqueezeRatio", 1.0)
    cmds.setAttr(f"{shape}.cameraScale", 1.0)
    _safe_set_attr(f"{shape}.displayResolution", 1)
    _safe_set_attr(f"{shape}.displayFilmGate", 1)
    _safe_set_attr(f"{shape}.displayGateMask", 1)
    _safe_set_attr(f"{shape}.overscan", 1.0)

    for item in frames:
        frame = item["frame"]
        matrix = item["matrix"]
        if flip_x:
            # Pre-multiply for Maya's row-major transform list so the camera
            # orientation flips while the world-space translation stays put.
            matrix = _matmul4(CAMERA_X_FLIP_MATRIX, matrix)
        focal = item.get("focal_length_mm")

        cmds.currentTime(frame, edit=True)
        cmds.xform(transform, worldSpace=True, matrix=matrix)
        cmds.setKeyframe(transform, attribute=["translate", "rotate", "scale"], time=frame)

        if focal is not None:
            cmds.setAttr(f"{shape}.focalLength", float(focal))
            cmds.setKeyframe(shape, attribute="focalLength", time=frame)

    if frames:
        cmds.currentTime(frames[0]["frame"], edit=True)

    if reference_media_path:
        _create_camera_reference_plane(transform, shape, reference_media_path)

    return transform


def import_bundle(
    bundle_dir,
    import_smplx_rig=True,
    import_body=True,
    import_smpc_mesh=False,
    import_camera=True,
    replace_camera=True,
    flip_camera_x=True,
    create_reference_plane=False,
):
    bundle_dir = os.path.abspath(bundle_dir)
    manifest_file = _manifest_path(bundle_dir)
    if not os.path.isfile(manifest_file):
        raise RuntimeError(f"GVHMR manifest not found: {manifest_file}")

    manifest = _load_json(manifest_file)
    files = manifest.get("files", {})

    imported_rig = ""
    imported_body = ""
    imported_mesh = ""
    camera_name = ""

    if import_smplx_rig:
        imported_rig = _import_smplx_rig(bundle_dir, files, replace_existing=True)

    if import_body:
        imported_body = _import_body(bundle_dir, files)

    if import_smpc_mesh:
        imported_mesh = _import_smpc_mesh(bundle_dir, files, replace_existing=True)

    if import_camera:
        camera_json = _resolve_bundle_file(bundle_dir, files.get("maya_camera_json", "camera_maya.json"))
        if not os.path.isfile(camera_json):
            raise RuntimeError(f"Maya camera JSON not found: {camera_json}")
        camera_data = _load_json(camera_json)
        reference_media = _reference_media_path(bundle_dir, files) if create_reference_plane else ""
        camera_name = _create_camera(
            camera_data,
            replace_existing=replace_camera,
            flip_x=flip_camera_x,
            reference_media_path=reference_media,
        )

    return {
        "bundle_dir": bundle_dir,
        "rig": imported_rig,
        "body_path": imported_body,
        "mesh": imported_mesh,
        "camera": camera_name,
    }


def _choose_bundle(*_):
    selection = cmds.fileDialog2(fileMode=3, caption="Select GVHMR Bundle Folder")
    if selection:
        cmds.textFieldButtonGrp("gvhmrBundleField", edit=True, text=selection[0])


def _run_import(*_):
    bundle_dir = cmds.textFieldButtonGrp("gvhmrBundleField", query=True, text=True)
    import_smplx_rig_value = cmds.checkBox("gvhmrImportSMPLXRigCheck", query=True, value=True)
    import_body_value = cmds.checkBox("gvhmrImportBodyCheck", query=True, value=True)
    import_smpc_mesh_value = cmds.checkBox("gvhmrImportSMPCMeshCheck", query=True, value=True)
    import_camera_value = cmds.checkBox("gvhmrImportCameraCheck", query=True, value=True)
    replace_camera_value = cmds.checkBox("gvhmrReplaceCameraCheck", query=True, value=True)
    flip_camera_x_value = cmds.checkBox("gvhmrFlipCameraXCheck", query=True, value=True)
    create_reference_plane_value = cmds.checkBox("gvhmrReferencePlaneCheck", query=True, value=True)

    try:
        result = import_bundle(
            bundle_dir,
            import_smplx_rig=import_smplx_rig_value,
            import_body=import_body_value,
            import_smpc_mesh=import_smpc_mesh_value,
            import_camera=import_camera_value,
            replace_camera=replace_camera_value,
            flip_camera_x=flip_camera_x_value,
            create_reference_plane=create_reference_plane_value,
        )
        message = "GVHMR import complete"
        if result.get("rig"):
            message += f"\nSMPLX Rig: {result['rig']}"
        if result.get("camera"):
            message += f"\nCamera: {result['camera']}"
        if result.get("body_path"):
            message += f"\nBody: {os.path.basename(result['body_path'])}"
        if result.get("mesh"):
            message += f"\nSMPC Mesh: {result['mesh']}"
        cmds.confirmDialog(title="GVHMR", message=message, button=["OK"])
    except Exception as exc:
        cmds.confirmDialog(title="GVHMR Import Failed", message=str(exc), button=["OK"], icon="critical")
        raise


def show():
    if cmds.window(WINDOW_NAME, exists=True):
        cmds.deleteUI(WINDOW_NAME)

    window = cmds.window(WINDOW_NAME, title="GVHMR Importer", sizeable=False)
    cmds.columnLayout(adjustableColumn=True, rowSpacing=8, columnOffset=("both", 10))

    cmds.text(label="GVHMR Bundle")
    cmds.textFieldButtonGrp(
        "gvhmrBundleField",
        label="Folder",
        buttonLabel="Browse",
        buttonCommand=_choose_bundle,
        columnWidth=[(1, 60), (2, 360), (3, 80)],
    )

    cmds.separator(height=8, style="in")
    cmds.checkBox("gvhmrImportSMPLXRigCheck", label="Import SMPLX skeletal rig", value=True)
    cmds.checkBox("gvhmrImportBodyCheck", label="Import FBX/Alembic body", value=True)
    cmds.checkBox("gvhmrImportSMPCMeshCheck", label="Import SMPC animated mesh cache", value=False)
    cmds.checkBox("gvhmrImportCameraCheck", label="Create animated camera", value=True)
    cmds.checkBox("gvhmrReplaceCameraCheck", label="Replace existing GVHMR camera", value=True)
    cmds.checkBox("gvhmrFlipCameraXCheck", label="Flip camera 180 degrees around X", value=True)
    cmds.checkBox("gvhmrReferencePlaneCheck", label="Attach reference video/image plane", value=False)

    cmds.separator(height=8, style="in")
    cmds.button(label="Import GVHMR Bundle", height=34, command=_run_import)
    cmds.setParent("..")
    cmds.showWindow(window)


if __name__ == "__main__":
    show()
