"""
GVHMR Maya Importer

Load a GVHMR bundle generated by ComfyUI-MotionCapture and build a Maya scene:
- import an FBX or Alembic body if present
- create/keyframe the GVHMR camera from camera_maya.json

Run in Maya's Script Editor:

    import gvhmr_maya_importer
    gvhmr_maya_importer.show()
"""

import json
import os
import struct
from array import array

import maya.cmds as cmds
import maya.api.OpenMaya as om


WINDOW_NAME = "gvhmrMayaImporterWindow"


def _manifest_path(bundle_dir):
    return os.path.join(bundle_dir, "manifest.json")


def _resolve_bundle_file(bundle_dir, value):
    if not value:
        return ""
    if os.path.isabs(value):
        return value
    return os.path.abspath(os.path.join(bundle_dir, value))


def _load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _read_array(file_obj, typecode, count):
    data = array(typecode)
    data.frombytes(file_obj.read(count * data.itemsize))
    return data


def _try_load_plugin(name):
    try:
        if not cmds.pluginInfo(name, query=True, loaded=True):
            cmds.loadPlugin(name)
        return True
    except Exception:
        return False


def _set_time_unit(fps):
    fps_int = int(round(float(fps)))
    time_units = {
        15: "game",
        24: "film",
        25: "pal",
        30: "ntsc",
        48: "show",
        50: "palf",
        60: "ntscf",
    }
    unit = time_units.get(fps_int, f"{fps_int}fps")
    try:
        cmds.currentUnit(time=unit)
    except Exception:
        cmds.warning(f"Could not set Maya time unit to {unit}")


def _import_body(bundle_dir, files):
    fbx_path = _resolve_bundle_file(bundle_dir, files.get("fbx", ""))
    abc_path = _resolve_bundle_file(bundle_dir, files.get("alembic", "") or files.get("abc", ""))
    glb_path = _resolve_bundle_file(bundle_dir, files.get("glb", ""))

    if fbx_path and os.path.isfile(fbx_path):
        _try_load_plugin("fbxmaya")
        cmds.file(
            fbx_path,
            i=True,
            type="FBX",
            ignoreVersion=True,
            mergeNamespacesOnClash=False,
            namespace="gvhmr",
            options="fbx",
            preserveReferences=True,
        )
        return fbx_path

    if abc_path and os.path.isfile(abc_path):
        _try_load_plugin("AbcImport")
        cmds.AbcImport(abc_path, mode="import")
        return abc_path

    if glb_path and os.path.isfile(glb_path):
        cmds.warning("Bundle contains GLB, but Maya does not import GLB by default. Provide an FBX or Alembic for direct Maya import.")
    else:
        cmds.warning("No FBX or Alembic body found in bundle.")

    return ""


def _convert_smpc_point(x, y, z):
    # SMPC vertices are in GVHMR/SMPL Y-up world space. Maya is also Y-up.
    return om.MPoint(float(x), float(y), float(z))


def _create_mesh_from_frame(mesh_name, vertices, faces, frame_index, num_verts, num_faces):
    offset = frame_index * num_verts * 3
    points = [
        _convert_smpc_point(vertices[offset + i * 3], vertices[offset + i * 3 + 1], vertices[offset + i * 3 + 2])
        for i in range(num_verts)
    ]
    face_counts = [3] * num_faces
    face_connects = [int(v) for v in faces]
    mesh_fn = om.MFnMesh()
    mesh_obj = mesh_fn.create(points, face_counts, face_connects)
    transform = om.MFnDagNode(mesh_obj).parent(0)
    transform_name = om.MFnDagNode(transform).fullPathName()
    return cmds.rename(transform_name, mesh_name)


def _load_smpc_mesh_data(path):
    with open(path, "rb") as f:
        magic = f.read(4)
        if magic != b"SMPC":
            raise RuntimeError(f"Not an SMPC file: {path}")

        num_frames = struct.unpack("<I", f.read(4))[0]
        num_verts = struct.unpack("<I", f.read(4))[0]
        num_faces = struct.unpack("<I", f.read(4))[0]
        fps = struct.unpack("<f", f.read(4))[0]
        f.read(64)
        has_camera = struct.unpack("<I", f.read(4))[0]
        img_w = struct.unpack("<I", f.read(4))[0]
        img_h = struct.unpack("<I", f.read(4))[0]
        vertices = _read_array(f, "f", num_frames * num_verts * 3)
        faces = _read_array(f, "I", num_faces * 3)

    return {
        "num_frames": num_frames,
        "num_verts": num_verts,
        "num_faces": num_faces,
        "fps": fps,
        "has_camera": has_camera,
        "img_width": img_w,
        "img_height": img_h,
        "vertices": vertices,
        "faces": faces,
    }


def _import_smpc_mesh(bundle_dir, files, replace_existing=True, max_frames=240):
    smpc_path = _resolve_bundle_file(bundle_dir, files.get("smpc_bin", ""))
    if not smpc_path or not os.path.isfile(smpc_path):
        cmds.warning("No SMPC mesh cache found in bundle.")
        return ""

    data = _load_smpc_mesh_data(smpc_path)
    num_frames = int(data["num_frames"])
    num_verts = int(data["num_verts"])
    num_faces = int(data["num_faces"])

    if num_frames > max_frames:
        raise RuntimeError(
            f"SMPC mesh cache has {num_frames} frames. "
            f"This diagnostic importer is capped at {max_frames} frames."
        )

    mesh_name = "GVHMR_SMPL_Mesh"
    target_group = "GVHMR_SMPL_Targets"
    if replace_existing:
        for name in (mesh_name, target_group):
            if cmds.objExists(name):
                cmds.delete(name)

    base_mesh = _create_mesh_from_frame(mesh_name, data["vertices"], data["faces"], 0, num_verts, num_faces)
    targets = []
    if not cmds.objExists(target_group):
        target_group = cmds.group(empty=True, name=target_group)

    for frame_index in range(num_frames):
        target_name = f"GVHMR_SMPL_Frame_{frame_index + 1:04d}"
        target = _create_mesh_from_frame(target_name, data["vertices"], data["faces"], frame_index, num_verts, num_faces)
        cmds.parent(target, target_group)
        targets.append(target)

    blendshape = cmds.blendShape(*(targets + [base_mesh]), name="GVHMR_SMPL_BlendShape")[0]
    cmds.setAttr(f"{target_group}.visibility", 0)

    _set_time_unit(data["fps"] or 24)
    cmds.playbackOptions(min=1, max=num_frames)

    for idx in range(num_frames):
        attr = f"{blendshape}.w[{idx}]"
        frame = idx + 1
        for key_frame, value in ((max(1, frame - 1), 0.0), (frame, 1.0), (min(num_frames, frame + 1), 0.0)):
            cmds.setAttr(attr, value)
            cmds.setKeyframe(attr, time=key_frame)

    cmds.currentTime(1, edit=True)
    cmds.select(base_mesh, replace=True)
    return base_mesh


def _delete_existing_camera(camera_name):
    if cmds.objExists(camera_name):
        try:
            cmds.delete(camera_name)
        except Exception:
            pass


def _create_camera(camera_data, replace_existing=True):
    camera_name = camera_data.get("camera_name", "GVHMR_Camera")
    if replace_existing:
        _delete_existing_camera(camera_name)

    transform, shape = cmds.camera(name=camera_name)
    if transform != camera_name:
        transform = cmds.rename(transform, camera_name)
        shapes = cmds.listRelatives(transform, shapes=True, fullPath=False) or []
        shape = shapes[0] if shapes else shape

    img_w = int(camera_data.get("img_width", 1920))
    img_h = int(camera_data.get("img_height", 1080))
    fps = float(camera_data.get("fps", 24))
    frames = camera_data.get("frames", [])

    _set_time_unit(fps)
    if frames:
        cmds.playbackOptions(min=frames[0]["frame"], max=frames[-1]["frame"])

    cmds.setAttr("defaultResolution.width", img_w)
    cmds.setAttr("defaultResolution.height", img_h)

    for item in frames:
        frame = item["frame"]
        matrix = item["matrix"]
        focal = item.get("focal_length_mm")

        cmds.currentTime(frame, edit=True)
        cmds.xform(transform, worldSpace=True, matrix=matrix)
        cmds.setKeyframe(transform, attribute=["translate", "rotate", "scale"], time=frame)

        if focal is not None:
            cmds.setAttr(f"{shape}.focalLength", float(focal))
            cmds.setKeyframe(shape, attribute="focalLength", time=frame)

    if frames:
        cmds.currentTime(frames[0]["frame"], edit=True)

    return transform


def import_bundle(bundle_dir, import_body=True, import_smpc_mesh=False, import_camera=True, replace_camera=True):
    bundle_dir = os.path.abspath(bundle_dir)
    manifest_file = _manifest_path(bundle_dir)
    if not os.path.isfile(manifest_file):
        raise RuntimeError(f"GVHMR manifest not found: {manifest_file}")

    manifest = _load_json(manifest_file)
    files = manifest.get("files", {})

    imported_body = ""
    imported_mesh = ""
    camera_name = ""

    if import_body:
        imported_body = _import_body(bundle_dir, files)

    if import_smpc_mesh:
        imported_mesh = _import_smpc_mesh(bundle_dir, files, replace_existing=True)

    if import_camera:
        camera_json = _resolve_bundle_file(bundle_dir, files.get("maya_camera_json", "camera_maya.json"))
        if not os.path.isfile(camera_json):
            raise RuntimeError(f"Maya camera JSON not found: {camera_json}")
        camera_data = _load_json(camera_json)
        camera_name = _create_camera(camera_data, replace_existing=replace_camera)

    return {
        "bundle_dir": bundle_dir,
        "body_path": imported_body,
        "mesh": imported_mesh,
        "camera": camera_name,
    }


def _choose_bundle(*_):
    selection = cmds.fileDialog2(fileMode=3, caption="Select GVHMR Bundle Folder")
    if selection:
        cmds.textFieldButtonGrp("gvhmrBundleField", edit=True, text=selection[0])


def _run_import(*_):
    bundle_dir = cmds.textFieldButtonGrp("gvhmrBundleField", query=True, text=True)
    import_body_value = cmds.checkBox("gvhmrImportBodyCheck", query=True, value=True)
    import_smpc_mesh_value = cmds.checkBox("gvhmrImportSMPCMeshCheck", query=True, value=True)
    import_camera_value = cmds.checkBox("gvhmrImportCameraCheck", query=True, value=True)
    replace_camera_value = cmds.checkBox("gvhmrReplaceCameraCheck", query=True, value=True)

    try:
        result = import_bundle(
            bundle_dir,
            import_body=import_body_value,
            import_smpc_mesh=import_smpc_mesh_value,
            import_camera=import_camera_value,
            replace_camera=replace_camera_value,
        )
        message = "GVHMR import complete"
        if result.get("camera"):
            message += f"\nCamera: {result['camera']}"
        if result.get("body_path"):
            message += f"\nBody: {os.path.basename(result['body_path'])}"
        if result.get("mesh"):
            message += f"\nSMPC Mesh: {result['mesh']}"
        cmds.confirmDialog(title="GVHMR", message=message, button=["OK"])
    except Exception as exc:
        cmds.confirmDialog(title="GVHMR Import Failed", message=str(exc), button=["OK"], icon="critical")
        raise


def show():
    if cmds.window(WINDOW_NAME, exists=True):
        cmds.deleteUI(WINDOW_NAME)

    window = cmds.window(WINDOW_NAME, title="GVHMR Importer", sizeable=False)
    cmds.columnLayout(adjustableColumn=True, rowSpacing=8, columnOffset=("both", 10))

    cmds.text(label="GVHMR Bundle")
    cmds.textFieldButtonGrp(
        "gvhmrBundleField",
        label="Folder",
        buttonLabel="Browse",
        buttonCommand=_choose_bundle,
        columnWidth=[(1, 60), (2, 360), (3, 80)],
    )

    cmds.separator(height=8, style="in")
    cmds.checkBox("gvhmrImportBodyCheck", label="Import FBX/Alembic body", value=True)
    cmds.checkBox("gvhmrImportSMPCMeshCheck", label="Import SMPC animated mesh cache", value=False)
    cmds.checkBox("gvhmrImportCameraCheck", label="Create animated camera", value=True)
    cmds.checkBox("gvhmrReplaceCameraCheck", label="Replace existing GVHMR camera", value=True)

    cmds.separator(height=8, style="in")
    cmds.button(label="Import GVHMR Bundle", height=34, command=_run_import)
    cmds.setParent("..")
    cmds.showWindow(window)


if __name__ == "__main__":
    show()
